### ISSUE TITLE
Project is not build

### ISSUE THREAD

**Issue by SaeedNoshadi89** [JunydDEV/kmp-recipes-mobile-app#1]
This project is not building on the latest version of android studio. kotlin plugin version and agp version is old

**Comment by JunydDEV** [comment]
Thanks for reporting this issue, I upgraded the kotlin and AGP versions. 
This project is now compatible with **Android Studio Iguana | 2023.2.1**

**Comment by JunydDEV** [comment]
This project is now compatible with the latest versions of AGP, Jetpack Compose, and Kotlin. Therefore I am closing this issue.
